async function toB64(f,maxW=640,maxH=640,q=0.72){return new Promise((res,rej)=>{const i=new Image(),r=new FileReader();r.onload=e=>{i.onload=()=>{const t=Math.min(maxW/i.width,maxH/i.height,1),c=document.createElement('canvas');c.width=Math.round(i.width*t);c.height=Math.round(i.height*t);c.getContext('2d').drawImage(i,0,0,c.width,c.height);res(c.toDataURL('image/jpeg',q))};i.src=e.target.result};r.onerror=rej;r.readAsDataURL(f)})}
function initRoleHint(){const me=storage.getToken()?.role;const hint=document.getElementById('hint');const sel=document.getElementById('role');if(me==='admin'){sel.value='user';Array.from(sel.options).forEach(o=>{if(o.value!=='user')o.disabled=true});hint.textContent='admin สร้างได้เฉพาะ user'}else if(me==='dev'){hint.textContent='dev สร้าง user/admin/dev'}}
async function reloadUsers(){const d=await api('listUsers');const tb=document.querySelector('#utbl tbody');tb.innerHTML='';const me=storage.getToken()?.role;d.items.forEach(u=>{const tr=document.createElement('tr');const canToggle = (me==='dev') || (me==='admin' && u.role==='user');tr.innerHTML=`
  <td>${u.id}</td><td>${u.user}</td><td>${u.fullname||''}</td><td>${u.dept||''}</td><td>${u.title||''}</td><td>${u.role}</td>
  <td>${u.status}</td>
  <td class='right'><button class='btn' data-id='${u.id}' data-status='${u.status==='active'?'inactive':'active'}' ${!canToggle?'disabled':''}>${u.status==='active'?'ปิดการใช้งาน':'เปิดการใช้งาน'}</button></td>`;tb.appendChild(tr)});}
document.getElementById('f').addEventListener('submit', async (e)=>{e.preventDefault();const user=document.getElementById('user').value.trim();const password=document.getElementById('pass').value;const fullname=document.getElementById('fullname').value;const dept=document.getElementById('dept').value;const title=document.getElementById('title').value;const status=document.getElementById('status').value;const role=document.getElementById('role').value;const f=document.getElementById('photo').files[0];let photoBase64='';if(f){photoBase64=await toB64(f)}try{await api('createUser',{payload:{user,password,fullname,dept,title,status,role,photoBase64}});alert('สร้างผู้ใช้สำเร็จ');e.target.reset(); await reloadUsers();}catch(err){alert(err.message);}});
document.addEventListener('click', async (e)=>{const btn=e.target.closest('#utbl button[data-id]'); if(!btn) return; const id=btn.dataset.id; const status=btn.dataset.status; if(confirm('ยืนยันเปลี่ยนสถานะเป็น '+status+' ?')){ try{ await api('updateUserStatus',{payload:{id,status}}); await reloadUsers(); }catch(err){ alert(err.message); } } });
document.addEventListener('DOMContentLoaded', ()=>{ initRoleHint(); reloadUsers(); });
